### ISSUE TITLE
Aggregation limit / minZ being ignored

### ISSUE THREAD

**Issue by dnomadb** [mapbox/trizilla#15]
The intent of `trizilla.inflate(<minZ>)` is to limit the number of aggregation levels that happens in trizilla; if the minZ is 0, trizilla should only output triangles at the input size; if 5, it should aggregate to the 5th parent level.

Right now, this is being ignored and it is aggregating all the way up.

cc: @ian29

**Comment by ian29** [comment]
minZ is actually a "minZ" in the sense that it is the smalled triangle size you want to output; that is, `aggregator` will aggregate until it's generated tiles of size `minZ`
