### ISSUE TITLE
trizilla-tile

### ISSUE THREAD

**Issue by dnomadb** [mapbox/trizilla#2]
**`trizilla-tile`** should take:
1. GeoJSON triangular features (as a stream)
2. A `tri∆` - the relationship between triangle size and zoom level (as a static arg)

and should output:
1. 

```
{
  TQI*: <truncated to tile>,
  tile: {x: <x>, y: <y>, z:<z>}
  features: [<geojson? or serialtiles>]
}
```

as a stream (ie, as a that tile is ready)
- Let's standardize this term: Tri Quad Index (TQI)

cc: @ian29

**Comment by ian29** [comment]
@dnomadb by `TQI <truncated to tile>` you mean the full id like `s2n2n2s2n2n` ? if so, why do we need this for tiling (if we already know the tile's x/y/z?

**Comment by dnomadb** [comment]
> you mean the full id like s2n2n2s2n2n

Hm, actually thought wrong. Mean to say the actual quadtree index.

Basically, I was thinking that the way to aggregate them was to use the quad as a hash - so as triangles "come in", their id can be parsed, and the quadtree can be used as the key.

The other options would be to:
1. Stringify the x, y z and use as a hash, or;
2. Structure the tiling object as such:

```
 {<x>: {
    <y>: {
      <z> { <the stuff above for each tile },
      <z> { <the stuff above for each tile },
      ...
    },
    <y>: {
      <z> { <the stuff above for each tile },
      <z> { <the stuff above for each tile },
      ...
    },
 <x>: { },
 ...
}
```

**Comment by ian29** [comment]
> Stringify the x, y z and use as a hash

i like this option best. we can do flatter object/arrays this way and jump through fewer logical hoops

**Comment by ian29** [comment]
grabbing this

**Comment by ian29** [comment]
let's pause on cli implementations. we can circle back and make this useful to other people, but let's make this useful to anyone first.
