### ISSUE TITLE
travis

### ISSUE THREAD

**Issue by ian29** [mapbox/trizilla#20]
we should introduce trizilla to señor travis

@dnomadb

**Comment by dnomadb** [comment]
@ian29 They have introduced, but travis is failing on comparison of the serialized features. The test passes locally, tho, so I am not sure what is up.
https://travis-ci.org/mapbox/trizilla/builds/52023467
Investigating.
https://github.com/mapbox/trizilla/pull/22

**Comment by ian29** [comment]
error was due to an errant newline, which is solved in #25. we're good here.
