### ISSUE TITLE
Array-based aggregation

### ISSUE THREAD

**Issue by dnomadb** [mapbox/trizilla#28]
Move from additive aggregation: https://github.com/mapbox/trizilla/blob/master/lib/aggregator.js#L9

To a system that checks for nulls (-999), pushes to array, and aggregates based on these arrays.

cc @ian29

**Comment by ian29** [comment]
@dnomadb this is implemented right?

**Comment by dnomadb** [comment]
Yes, implemented in `no-serialize`
