### ISSUE TITLE
min triangle size should be an argument

### ISSUE THREAD

**Issue by ian29** [mapbox/trizilla#3]
and maybe default to 3 @dnomadb ?

https://github.com/mapbox/trizilla/blob/better-stream/index.js#L7

**Comment by dnomadb** [comment]
In practice, our minimum will be 5; however, maybe the default can be no aggregation at all, just inflation (eg, same as input)? Either that, or a specified number of levels "down" from the input.

**Comment by ian29** [comment]
>  maybe the default can be no aggregation at all, just inflation (eg, same as input)? Either that, or a specified number of levels "down" from the input.

yeah this makes better conceptual sense to me. will do.

**Comment by ian29** [comment]
implemented in `inflator-wrapper` branch
https://github.com/mapbox/trizilla/blob/inflator-wrapper/index.js#L19
