### ISSUE TITLE
Standardize qt

### ISSUE THREAD

**Issue by dnomadb** [mapbox/trizilla#9]
The qt (QuadTri) is the modified quadtree index value we are basing all triangle work on. It has gone by many names since its inception. We need to standardize its use here and in https://github.com/mapbox/make-surface/
- [x] `quadtree --> qt` (unless actually quadtree)
- [x] `index --> qt` (unless actually another kind of index)
- [x] `quadtri --> qt`
- [x] `otherrandomthingswevecalledit --> qt`

cc: @ian29

**Comment by ian29** [comment]
this happened.
